### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by velimir** [gar1t/erlang-patterns#31]
Would you please add a license to the repo?

**Comment by gar1t** [comment]
What sort of license would you suggest? I was looking over creative commons ecosystem of licenses but got swamped in details and legalize. I'd like this to be straight forward and totally open.

**Comment by velimir** [comment]
I would suggest to go with [CC0 1.0 (Public Domain Dedication)](https://creativecommons.org/publicdomain/zero/1.0/) from the creative commons family, which is the most open license that doesn't require attribution for your own work.

The legal code can be found on the official page: https://creativecommons.org/publicdomain/zero/1.0/legalcode

**Comment by gar1t** [comment]
I added this:

https://choosealicense.com/licenses/cc-by-sa-4.0/

**Comment by velimir** [comment]
thank you!
