### ISSUE TITLE
Lists not rendered as lists?

### ISSUE THREAD

**Issue by derek121** [gar1t/erlang-patterns#8]
Looking at chain.md, it includes a markdown bulleted list. The generated HTML does include it as a &lt;ul>, but when rendered in a browser there are no bullets- they're just three separate lines.

Just curious if this is intended, thanks.

**Comment by derek121** [comment]
Also- this was seen on Chrome, Firefox, and Safari on OS X.

**Comment by gar1t** [comment]
This is fixed. The template resets the CSS for everything and it just needed to be re-enabled in templates/pattern.html by wrapping with class="real-lists".
